### PR TITLE
feat: add an option to provide better blur effect

### PR DESCRIPTION
**Pull request by FlysoftBeta**

### CODE REVIEW

**Review by MicroCBer — CHANGES_REQUESTED** [review]
It shouldn't be a feature in the main background effect config as the masked background already had a mask layer. It should be a feature of masked background.

The main difference between `filter: blur` and `backdrop-filter: blur` is the first one is using kDecal as tile mode and the second one is using kMirror iirc. kMirror would repeat the shader vertically and horizontally which is ~4x slower under my subjective inference which is of great concern when using videoes as the backdrop. It shouldn't be the default option. The recommended operation is to enlarge the scale so that the edge won't be seen.

**Comment by MicroCBer** [comment]
Also, reference #14

**Comment by MicroCBer** [comment]
> It shouldn't be a feature in the main background effect config as the masked background already had a mask layer. It should be a feature of masked background.

**Comment by FlysoftBeta** [comment]
> > It shouldn't be a feature in the main background effect config as the masked background already had a mask layer. It should be a feature of masked background.

However, there isn't any blur options in masked background. I think putting this option to the main options is better rather than making it a feature of masked background. If we put it in masked background, we will have duplicate options to set blurry background, which will make the users confused.

**Pull request closed without merging**
